#:schema node_modules/wrangler/config-schema.json
name = "maddiemasiello-com"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"
